### ISSUE TITLE
Python's async_lru requirement

### ISSUE THREAD

**Issue by huguei** [SIDN/CycleHunter#20]
I suggest adding the python library requirement "async_lru" to the README section. For ubuntu it's just "sudo pip install async_lru".
Thanks!

**Comment by gmmoura** [comment]
thanks , @huguei ! will do

**Comment by gmmoura** [comment]
@huguei : did you make a PR? I could not find it
if you do, I can accept it and close the issue
thanks

**Comment by huguei** [comment]
Done in #21 thanks!

**Comment by gmmoura** [comment]
fixed! thanks
