### ISSUE TITLE
The DNS query name does not exist in Step 4

### ISSUE THREAD

**Issue by SvenVD-be** [SIDN/CycleHunter#7]
For some domains I get

Step 4: sort which ones are cyclic

analyzying xxxxxx.zone.. Domain 12 from 14
The DNS operation timed out after 5.1041343212127686 seconds
The DNS operation timed out after 5.105474233627319 seconds
<class 'dns.exception.Timeout'>
The DNS query name does not exist: N.
The DNS query name does not exist: N.
The DNS query name does not exist: X.
The DNS query name does not exist: X.
The DNS query name does not exist: D.
The DNS query name does not exist: D.
The DNS query name does not exist: O.
The DNS query name does not exist: O.
The DNS query name does not exist: M.
The DNS query name does not exist: M.
The DNS query name does not exist: A.
The DNS query name does not exist: A.
The DNS query name does not exist: I.
The DNS query name does not exist: I.
The DNS query name does not exist: N.
The DNS query name does not exist: N.

So it seems that if all NS of a zone do not reply or do not reply with useful data, the script does something not expected or does not have a managed case to handle it?

**Comment by SvenVD-be** [comment]
I tried a quick fix in https://github.com/SIDN/CycleHunter/pull/8

**Comment by gmmoura** [comment]
perfect! I merged your PR already, so I'll makr this as fixed
